linters-settings:
  gocyclo:
    min-complexity: 18
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
    enable-all: true
  testifylint:
    disable:
      - require-error
      - error-nil
      - formatter
      - encoded-compare
  revive:
    rules:
      - name: var-naming
        arguments:
          - [] # AllowList
          - ["DTO"] # DenyList
      - name: unused-parameter
        disabled: false

linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell
    - govet
    - unused
    - errcheck
    - copyloopvar
    - gosimple
    - ineffassign
    - staticcheck
    - testifylint
    - whitespace
    - bodyclose
    - inamedparam
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .github
    - resources
  exclude:
    - should have a package comment
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
